version: '3'
services:
  product-service:
    build:
      context: ../../
      dockerfile: ./examples/product-service/Dockerfile
    volumes:
     - ../../microdocs-cloud-rest-client/dist:/app/@microdocs/product-service/node_modules/@microdocs/cloud-rest-client:ro
     - ../../microdocs-cloud-rest-client-node/dist:/app/@microdocs/product-service/node_modules/@microdocs/cloud-rest-client-node:ro
     - ./src:/app/@microdocs/product-service/src:ro
     - ./dist:/app/@microdocs/product-service/dist
    ports:
     - 3001:3000
     - 5859:5858
    networks:
     - default

networks:
  default:
    external:
      name: example-network
