version: '3'
services:
  microdocs-cloud-rest-client-angular2:
    build:
      context: ../
      dockerfile: ./microdocs-cloud-rest-client-angular2/Dockerfile
    volumes:
     - ./src:/app/@microdocs/cloud-rest-client-angular2/src:ro
     - ./dist:/app/@microdocs/cloud-rest-client-angular2/dist
     - ../microdocs-cloud-rest-client/dist:/app/@microdocs/cloud-rest-client-angular2/node_modules/@microdocs/cloud-rest-client
