application:
  name: auditlog
  profiles: development

logger:
  level: verbose

mongodb:
  url: mongodb://mongodb/auditlog

amqp:
  url: amqp://rabbitmq
  exchange: mybus
  queue: audit-log
  routingKey: #
