version: '3'
services:
  examples-order-service:
    build:
      context: ../../
      dockerfile: ./examples/order-service/Dockerfile
    volumes:
     - ../../microdocs-cloud-rest-client/dist:/app/@microdocs/order-service/node_modules/@microdocs/cloud-rest-client:ro
     - ../../microdocs-cloud-rest-client-node/dist:/app/@microdocs/order-service/node_modules/@microdocs/cloud-rest-client-node:ro
     - ./src:/app/@microdocs/order-service/src:ro
     - ./dist:/app/@microdocs/order-service/dist
    ports:
     - 3000:3000
     - 5858:5858
    networks:
     - default

networks:
  default:
    external:
      name: example-network

