version: '3'
services:
  examples-order-client:
    build:
      context: ../../
      dockerfile: ./examples/order-client/Dockerfile
    volumes:
     - ../../webscale-rest-client/dist:/app/@webscale/order-client/node_modules/@webscale/rest-client:ro
     - ../../webscale-rest-client-angular2/dist:/app/@webscale/order-client/node_modules/@webscale/rest-client-angular2:ro
     - ./src:/app/@webscale/order-client/src:ro
     - ./dist:/app/@webscale/order-client/dist
    ports:
     - 4200:4200

